project:
  type: website
  output-dir: docs

website:
  title: "Martinas Jucys Brady"
  favicon: assets/android-chrome-512x512.png
  back-to-top-navigation: true
  navbar:
    pinned: true
    logo: assets/android-chrome-512x512.png
    right:
      - href: index.qmd
        icon: house
        text: Home
      - href: about.qmd
        icon: person-circle        
        text: About Me
      - href: projects.qmd
        icon: file-earmark-text
        text: Projects
      - icon: github
        href: https://github.com/martinas-jucysbrady  
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/martinasjucysbrady/
        target: _blank
      - icon: person-rolodex
        href: assets/mypdf.pdf
        target: _blank
  page-footer: 
    left: "Â© Martinas Jucys Brady, 2026"    
    right: "Built with [Quarto](https://quarto.org/)"


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



