project:
  type: website
  output-dir: docs
  resources: 
   - projects\business_strategy\business_strategy_consultancy_report.pdf
   - projects\business_strategy\business_strategy_presentation.pdf
   

website:
  title: "Martinas Jucys Brady"
  favicon: assets/mjb_favicon.png
  back-to-top-navigation: true
  navbar:
    title: false
    pinned: true
    logo: assets/mjb_favicon.png
    right:
      - href: projects.qmd
        icon: file-earmark-text
        text: Projects
      - href: about.qmd
        icon: person-circle        
        text: About
      - icon: github
        href: https://github.com/martinas-jucysbrady  
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/martinasjucysbrady/
        target: _blank
      - text: "**CV**"
        href: assets/CV.pdf
        target: _blank
      
  page-footer: 
    left: "Â© Martinas Jucys Brady, 2026"    
    right: "Built with [Quarto](https://quarto.org/)"


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    mainfont: sans-serif
    toc: false
    page-layout: full



